# Generated by Django 2.2.5 on 2019-09-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc_code', models.TextField(db_index=True)),
                ('bank_id', models.PositiveIntegerField()),
                ('branch', models.TextField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
            ],
        ),
    ]
